### ISSUE TITLE
new images for map command

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/qrm2#112]
http://www.mapability.com/ei8ic/maps/maps.php

**Comment by 0x5c** [comment]
Will depend on #83 for attribution

**Comment by 0x5c** [comment]
My current goal is metadata+emojis, since the emojis are already known. The images are not yet chosen  nor processed.

**Comment by classabbyamp** [comment]
email sent to EI8IC

**Comment by classabbyamp** [comment]
can get bumped to v2.2.0 if not ready before all other issues are completed.

**Comment by classabbyamp** [comment]
Ok we should add back:

- [CQ Zones](https://github.com/miaowware/qrm2/blob/bd5ba08a3c0e2fc6ee73c3ff4cc4b3811d39c138/resources/images/map/cqmap.png)
- [ITU Zones](https://github.com/miaowware/qrm2/blob/bd5ba08a3c0e2fc6ee73c3ff4cc4b3811d39c138/resources/images/map/itumap.png)

And add:

- [ITU Regions](https://www.mapability.com/ei8ic/maps/regions.php)

And update:

- [ARRL and RAC Sections (2nd img)](https://www.mapability.com/ei8ic/maps/sections.php)

All of these should have attribution (#130) to EI8IC.
