### ISSUE TITLE
ae7q application lookup

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/qrm2#168]
Continuation of #95 

- [x] application details
- [x] application history
    - [x] by callsign
    - [x] by FRN
    - [x] by licensee ID

some code exists in exts/ae7q.py already. needs refactor and completion.

**Comment by classabbyamp** [comment]
will be done with #195, this issue is for implementing it in the bot

**Comment by 0x5c** [comment]
Closing this, will be part of #195
