### ISSUE TITLE
Suggestion: Phonetic weight command.

### ISSUE THREAD

**Issue by EliseYL73** [miaowware/qrm2#170]
The command would state how heavy the phonetic weight of a callsign is.

Example: 
"?pw AA1ABC"
"The Phonetic Weight of AA1ABC is 11"

**Comment by classabbyamp** [comment]
phonetic weight should be calculated by the number of syllables in the nato phonetic representation of the phrase (including numbers).

Ignore punctuation and chars not in the nato list? should be easy with a lookup table.
