### ISSUE TITLE
plain METAR weather

### ISSUE THREAD

**Issue by bruceyang1998** [miaowware/qrm2#171]
`?wttr` gives a pictoral representation of weather given an ICAO code. However, sometimes a plain text representation may be more appropriate. 

`?metar [ICAO]`

e.g.
```
?metar KATL
> KATL 170452Z 36009KT 10SM BKN150 BKN250 11/M02 A3045 RMK AO2 SLP310 T01061022 401830106
```

Can potentially get METAR from https://www.aviationweather.gov/metar/data?ids=[ICAO]&format=raw&hours=0&taf=off&layout=off

**Comment by 0x5c** [comment]
The data used for wttr is never passing through the bot. Everything happens on [wttr.in](https://wttr.in/) ([chubin/wttr.in](https://github.com/chubin/wttr.in)), which is just a wrapper for [`wego`](https://github.com/schachmat/wego), which in-turn depends on a weather API.  
*Btw, wttr.in accepts a wide range of place identifiers. See `?h wttr` for the full list.*

So implementing that command would require entirely new work. It would be interesting though, se we'll have look at what we can do.

**Comment by 0x5c** [comment]
Also available: https://avwx.rest/

**Comment by 0x5c** [comment]
## Notes
- aviationweather.gov
  - includes easy to parse data with comments (HTML)
    ![image](https://user-images.githubusercontent.com/5877043/97793540-bdb10600-1bc3-11eb-8158-fbb334fc3d17.png)
  - multiple hours available with query argument
  - TAF available with query argument
- avwx
  - 4k queries per day with free account
  - REST API
