### ISSUE TITLE
Move map/plan code to a single function?

### ISSUE THREAD

**Issue by 0x5c** [miaowware/qrm2#189]

**Comment by classabbyamp** [comment]
it *might* also be possible to merge in the pfx command stuff into this after #244. Maybe.

**Comment by 0x5c** [comment]
I doubt
`plan` and `map` both have the same format: emoji:title:description:source/attribution:image
`pfx` has format emoji:title:description:sections

**Comment by 0x5c** [comment]
@classabbyamp Since thisis currently a question, ping for review/discussion of this soon
