### ISSUE TITLE
ham ?wiki command

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/qrm2#192]
Once we see how the wiki works it may be possible to `?wiki <search terms>` and return either an existing page or a search results page, similar to DuckDuckGo's bang search for wikipedia, which uses the search URL. Wikipedia will redirect to the proper page if the search terms match, and otherwise will show results.

**Comment by classabbyamp** [comment]
this will require a wiki to be running before it can be implemented.

**Comment by classabbyamp** [comment]
Unless something big changes, this is `wontfix` in my eyes.

**Comment by 0x5c** [comment]
What about a 'freezed' tag + closing the issue?
