### ISSUE TITLE
Convert "concatenable" f-strings?

### ISSUE THREAD

**Issue by 0x5c** [miaowware/qrm2#193]
```py
# From
f"text{var}"
# to
"text" + var
```

**Comment by classabbyamp** [comment]
https://stackoverflow.com/a/43213810

F-strings may be marginally faster

**Comment by 0x5c** [comment]
Although, the accepted answer mentions different timings

**Comment by classabbyamp** [comment]
I see 54 results for `f"(\{.+|.+\})"` (an f-string with a `{` at the beginning or a `}` at the end. Do we want to go through and change these or s it fine as is. Seems like a _very_ marginal difference in timing, so this would mostly be a stylistic choice.

**Comment by 0x5c** [comment]
Since this is stylistic, I guess it will be better to review and discuss that together

**Comment by 0x5c** [comment]
@classabbyamp for review/discussion of this soon

**Comment by 0x5c** [comment]
Review results: we're dropping this
