### ISSUE TITLE
TypeError on ?rq us e

### ISSUE THREAD

**Issue by waterlubber** [miaowware/qrm2#201]
**Describe the bug**
Instead of giving me wonderful Extra questions that I can flex with, the bot gives the following error in Discord chat:
```
TypeError: can't compare offset-naive and offset-aware datetimes

CommandInvokeError
```

**To Reproduce**
1. Run `?rq us e` or `?rq us extra`
2. Observe result

**Expected behavior**
Extra question is ejected from the bot instead of e r r o r

**Screenshots**
![image](https://user-images.githubusercontent.com/7517025/74775055-e4602400-5262-11ea-8003-1793128d066a.png)

**Additional context**
Seems to work with other pools, like us g

**Comment by classabbyamp** [comment]
Known about this since last night. Know what the issue probably is, should be a quick fix.

**Comment by 0x5c** [comment]
Could be fit for a bugfix release too
