### ISSUE TITLE
Check why flake8_py3 does not report status

### ISSUE THREAD

**Issue by MadIceTea** [miaowware/qrm2#222]
**Describe the bug**
flake8_py3 fails to correctly report the status of CI/CD checks in PRs to this GitHub.

**To Reproduce**
1. Submit a PR with a code change.
2. See an error in the 'merge is blocked' section.

**Expected behavior**
The error is that flake8_py3 does not ever report it's status, even when waiting on the page for 10 minutes or more. It should either checkout as a pass or fail status and report back to the PR as an automated CI/CD check.

**Screenshots**
![Here's one](https://user-images.githubusercontent.com/7548448/79681409-f7de2b80-81ce-11ea-925e-60202b337eb0.jpg)

**System (include if related to running the bot):**
 - Almost certainly unrelated, but just in case... 
![this is it](https://user-images.githubusercontent.com/7548448/79681443-31169b80-81cf-11ea-9312-00a1de9127bf.jpg)

--

**Additional context**
None to report.

**Comment by classabbyamp** [comment]
It usually works, and is working on the other open PR. You probably aren't doing the right events to trigger it
