### ISSUE TITLE
Italian bandplan

### ISSUE THREAD

**Issue by Pacmannion** [miaowware/qrm2#225]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add the Italian bandplan, available here: http://www.arimi.it/wp-content/Plan/BP%20HF%202013%2032.pdf
**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by 0x5c** [comment]
*Notes:*
- HF-only
- Italian language
- Format is not too big, simple colours

ID: `it-hf`
