### ISSUE TITLE
New command: dB conversions

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/qrm2#231]
specificially requested: dBm <-> W or mW

Could also do: dBW, dBd, dBi, dBA, etc

**Comment by 0x5c** [comment]
I'd say let's do them all

**Comment by classabbyamp** [comment]
proposed syntax:
```
?db <value> <unit1> <unit2>
?db 10 dbm mw
?db -123 dbw dbm
?db 12 w dbw
```

**Comment by classabbyamp** [comment]
# Valid Units

Will need to check that `unit2` is a valid conversion from `unit1`

## Volts

Units: `dBV, dBuV, dBµV, dBmV, V, uV, µV, mV`

| Unit      | Relative to                         |
|-----------|-------------------------------------|
| dBV       | 1 V                                 |
| dBuV/dBµV | 1 µV                                |
| dBmV      | 1 mV                                |

## Power

Units: `dBf, dBm, dBmW, dBW, dBk, fW, mW, W, kW`

| Unit      | Relative to                         |
|-----------|-------------------------------------|
| dBf       | 1 fW                                |
| dBm/dBmW       | 1 mW                                |
| dBW       | 1 W                                 |
| dBk       | 1 kW                                |

## Antenna

Units: `dBi, dBd, dBq`

| Unit      | Relative to                         |
|-----------|-------------------------------------|
| dBi       | isotropic antenna                   |
| dBd       | dipole antenna (0 = 2.15 dBi)       |
| dBq       | quarterwave antenna (0 = -0.85 dBi) |
