### ISSUE TITLE
Australian Band Plan

### ISSUE THREAD

**Issue by yaakov-h** [miaowware/qrm2#242]
The band plan for Australian is published by the Wireless Institute of Australia (WIA) [here](https://www.wia.org.au/members/bandplans/data/documents/Australian%20Band%20Plans%20100404.pdf).

There's not a lot of colour and the information is spread across many pages, so it probably needs to be composited by hand into a single image, unless you're OK with the bot just providing a link to the PDF or similar.

**Comment by classabbyamp** [comment]
We'd definitely prefer an image, but we're considering all options at this point.

**Comment by classabbyamp** [comment]
[Here's](https://vkradioamateurs.org/wp-content/uploads/2018/05/VK-Band-Plan-Quick-Reference-1.pdf) a quick reference version from RASA. It should work well.

**Comment by yaakov-h** [comment]
ooh I didn't know about that, that looks much nicer.

**Comment by 0x5c** [comment]
Oh ya I like that one
