### ISSUE TITLE
Contributors list in README

### ISSUE THREAD

**Issue by MadIceTea** [miaowware/qrm2#287]
Suggestion to show a list of contributors directly in the README of the repository

(per an idea discussed during #221)

**Comment by classabbyamp** [comment]
As noted by @0x5c in her review [here](https://github.com/0x5c/minibot/pull/22#discussion_r513249600), we strive to not clobber the commit authorship of outside contributions. Thus, github will display the contributors to this repo on the main page, like so:

![image](https://user-images.githubusercontent.com/5366828/97513301-3fa1f480-1962-11eb-95f5-fc796ab5ba51.png)

**Comment by MadIceTea** [comment]
OK thanks, I think that settles this question.

Let's close this issue.
