### ISSUE TITLE
Documentation: Redirect all issues for map and plans (and such) to qrm-resources

### ISSUE THREAD

**Issue by 0x5c** [miaowware/qrm2#307]
Readme, contributing guidelines?, `?issue`, and any other place where it could go

**Comment by classabbyamp** [comment]
if this goes in contrib guidelines, not sure what to do. we have [DEVELOPING.md](DEVELOPING.md) in this repo, but [CONTRIBUTING.md](CONTRIBUTING.md) is in the `.github` repo.

**Comment by 0x5c** [comment]
I'd say that it being prominently mentioned in the readme would be good

Should also be mentioned in issue templates

**Comment by classabbyamp** [comment]
Issue templates are also at the org level, so idk

**Comment by 0x5c** [comment]
Can't we add an issue template file here?
