### ISSUE TITLE
greyline image is cached by discord

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/qrm2#308]
suggest adding a url param nonce so it is always retrieved

**Comment by classabbyamp** [comment]
nonce should be a hashed datetime, at an interval that is reasonable (maybe ~10min)

**Comment by 0x5c** [comment]
Essentially:
1. Dump a UNIX timestamp int
2. Trim enough LSBs to get ~10m precision
3. Use whatever simple hash function provided by python (the timestamp *should* be unique anyway, so unneeded?)
