### ISSUE TITLE
?ae7q and ?qrz should validate inputs

### ISSUE THREAD

**Issue by franrogers** [miaowware/qrm2#345]
### Is your feature request related to a problem? Please describe.

The ?ae7q and ?qrz commands should validate inputs, since their inputs are being interpolated into URLs, and special characters could enable mischief.

### Describe the solution you'd like

Ensure only alphanumeric inputs are being passed into these commands.

**Comment by classabbyamp** [comment]
these commands are going to be improved per #195 and #58, so we can do this during that process.
