### ISSUE TITLE
ensure ghcr repo is lowercase in workflow

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/qrm2#413]
### Bug description

docker push fails if repo has caps (maybe image name too?) 

### Steps to reproduce

1. run the workflow from an account/org with caps in the name
1. see error

### Expected behaviour

push works

### How did you download qrm?

Git (clone)

### How are you running qrm?

I do not know (user of official instance)

### What qrm version are you running?

dev

**Comment by 0x5c** [comment]
Huh? Where did that show up?

**Comment by LFGSaito** [comment]
I was playing around with a clone of this repo, and tried out a few of the actions, and on one of my runs, I ran into the error. 
https://github.com/LFGSaito/owlbotv2/runs/2299238055?check_suite_focus=true
