### ISSUE TITLE
Solar command caching

### ISSUE THREAD

**Issue by alekm** [miaowware/qrm2#441]
### Bug description

Discord will cache images when produced from a URL, causing solar data images that can be days or weeks old.

### Steps to reproduce

<command>solar

### Expected behaviour

Suspect serving an image the same way the svg images are gathered and producing with `attachment://` would suffice with a realtime image instead of a cached image from the URL

### How did you download qrm?

Git (clone)

### How are you running qrm?

Docker

### What qrm version are you running?

v2.7.4

**Comment by classabbyamp** [comment]
this is a known issue: #322

Sending a file is not optimal, because the time spent uploading the image is blocking, which is not great, especially for large images.

**Comment by alekm** [comment]
Can this be fixed by adding a timecode to the url? (e.g. https://www.hamqsl.com/solarsun.php?1648097678)

**Comment by classabbyamp** [comment]
hamqsl's images don't support giving any kind of timestamp in a way that affects the generated image (like the greyline map does), and adding a unique nonce just for discord doesn't work (see #308 and #318, especially https://github.com/miaowware/qrm2/issues/318#issuecomment-762095932).

We've spent a while on this issue and the only reasonable solution seems to be making a small cdn/image proxy, which we haven't had time to implement yet.
