### ISSUE TITLE
Random Questions command not working in DMs

### ISSUE THREAD

**Issue by allieuwu** [miaowware/qrm2#442]
### Describe the Bug

DMing qrm with the ?rq command results in an unanswerable question prompt, reactions don't work to interact. Bot is still able to edit messages, as it times out after the 5 minutes.

### Steps To Reproduce

Message qrm#5867 with a random question command, ex. ?rq ca b

### Expected behavior

Should produce a random, answerable hamstudy question prompt, that is interacted with through reactions

### Screenshots, Logs, etc.

![image](https://user-images.githubusercontent.com/96448163/166197459-8fbf6c0b-318d-414e-862a-43bd27770efc.png)
![image](https://user-images.githubusercontent.com/96448163/166197482-ca2ca5ba-a132-4543-9803-f9a08f44547e.png)

**Comment by classabbyamp** [comment]
confirmed, will look into it. seems likely to be caused by an api change
