### ISSUE TITLE
message.content will become privileged intent

### ISSUE THREAD

**Issue by Frigyes06** [miaowware/qrm2#451]
### Bug description

From august 31, message.content will be only available for verified bots.
https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ

### Steps to reproduce

na

### Expected behaviour

ba

### How did you download qrm?

I do not know (user of official instance)

### How are you running qrm?

I do not know (user of official instance)

### What qrm version are you running?

na

### Environment

na

### Logs

```none
na
```

### Additional context, screenshots, etc

na

**Comment by classabbyamp** [comment]
> WHO IS IMPACTED?
> This change applies only to verified bots and apps, which means those that are in 75 or more servers.

This does not affect qrm. The official instance is in fewer than 75 servers, and we already have the message content intent declared:

https://github.com/miaowware/qrm2/blob/ef6f01d1a317d6912bdb9b9a0facf96896b0808c/main.py#L52-L53
