### ISSUE TITLE
release CI: release creation action is borken/unmaintained

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/qrm2#464]
https://github.com/actions/create-release

**Comment by 0x5c** [comment]
From the list of alternatives in the README, only two seem to be capable of doing what we need, the others don't have a way to specify the body of the release (or even the title!).

[softprops/action-gh-release](https://github.com/softprops/action-gh-release)
[ncipollo/release-action](https://github.com/ncipollo/release-action)
