### ISSUE TITLE
QRMBot Crashing on Random Call queries "validation errors for QrzDataModel"

### ISSUE THREAD

**Issue by m0ze1r** [miaowware/qrm2#466]
### Bug description

There was a crash when

1. Callsign was queried 

![image](https://user-images.githubusercontent.com/63652835/213525940-bd813e0a-e155-4584-bfda-bcd1479a14ce.png)

![image](https://user-images.githubusercontent.com/63652835/213528512-a3126e63-ff98-4a1f-bc5e-54f1873c8729.png)

![image](https://user-images.githubusercontent.com/63652835/213528642-d7b89cee-e4f8-4d62-a3fd-dd762a4071b3.png)

### Steps to reproduce

1. Query "VP5WS" "TA8BB" "VK9DX"
2. Crash
3. Query W1AW
4. Works fine?

### Expected behaviour

![image](https://user-images.githubusercontent.com/63652835/213527718-f25514bc-982f-466a-985b-a00beeb4cdee.png)

I'd imagine there are a bunch more other calls that this happens with and it may be an issue on QRZ side but I'm lodging this in-case its something that's on QRM side also

### How did you download qrm?

I do not know (user of official instance)

### How are you running qrm?

I do not know (user of official instance)

### What qrm version are you running?

2.9.0 (6b0cdb6)

### Logs

```none
pydantic.error_wrappers.ValidationError: 2 validation errors for QrzDataModel
efdate
  time data '0000-00-00' does not match format '%Y-%m-%d' (type=value_error)
expdate
  time data '0000-00-00' does not match format '%Y-%m-%d' (type=value_error)

CommandInvokeError
```

**Comment by classabbyamp** [comment]
known issue with a probable known cause, will just need time to fix it sometime soon
 https://github.com/miaowware/callsignlookuptools/issues/24
