### ISSUE TITLE
metar broken

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/qrm2#475]
404, seems the data source changed something

**Comment by 0x5c** [comment]
The site seems to have been fully rewritten, now with [an actual `/api` route](https://aviationweather.gov/data/api/) with openapi, and true raw output. The query format seems very similar, but will require that the TAF boolean be changed (`on/off -> true/false`) and that the `hours` parameter be made conditional. The HTML parsing will also not be needed anymore.

This will require a bit of refactor but should be easy enough.
