### ISSUE TITLE
Solarweather Command Request Failed

### ISSUE THREAD

**Issue by Coolguy3289** [miaowware/qrm2#478]
### Bug description

When running the ?solarweather command, the following message is returned:
![image](https://github.com/miaowware/qrm2/assets/12205727/7a721455-f91f-4902-b06b-7b6a5ef02141)

### Steps to reproduce

1. Run ?solarweather

### Expected behaviour

HTTP Fetch should return the results

### How did you download qrm?

I do not know (user of official instance)

### How are you running qrm?

I do not know (user of official instance)

### What qrm version are you running?

v2.9.1

**Comment by classabbyamp** [comment]
fixed by #474
