### ISSUE TITLE
return of the tex cmd?

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/qrm2#65]
see [mathbot](https://github.com/DXsmiley/mathbot/blob/master/mathbot/modules/latex/__init__.py) for inspiration

**Comment by thxo** [comment]
I'm down to give this a shot. Any requirements (e.g. dependencies that can be installed with the OS) that you have on your end?

**Comment by classabbyamp** [comment]
if you look at mathbot, it's all done via a [web API](http://rtex.probablyaweb.site/), so it should be pretty easy, it just needs to happen.

*However:*

After v2.2.0 is released, @0x5c and I will be doing some structural changes to the core of the bot, so it may be best to wait.

**Comment by 0x5c** [comment]
Considering the structural changes planned, this shouldn't cause a problem if written as a new extension+cog. You'd only need to make no changes to other `.py` files (except the templates for options/keys, don't forget to add the extension to the default list).

**Comment by 0x5c** [comment]
But you need to wait for 2.2.0 to be released, since it will include a lot of linting. (see #142)

**Comment by 0x5c** [comment]
@thxo You can now safely start working on this :)
